abstract class AppStates{}
class AppInitialState extends AppStates{}
class GetUserSuccessState extends AppStates{}
class ChangeEyeState extends AppStates{}
class UserSingOutSuccessState extends AppStates{}
class GetUserErrorState extends AppStates{}
class ChangeBottomNavState extends AppStates{}
class GetCategoryLoadingState extends AppStates{}
class GetSingleCategoryLoadingState extends AppStates{}
class GetCategorySuccessState extends AppStates{}
class GetSingleCategorySuccessState extends AppStates{}
class GetCategoryErrorState extends AppStates{}
class GetSingleCategoryErrorState extends AppStates{}
class GetProductLoadingState extends AppStates{}
class GetProductSuccessState extends AppStates{}
class GetProductErrorState extends AppStates{}
class GetBannerLoadingState extends AppStates{}
class GetBannerSuccessState extends AppStates{}
class GetBannerErrorState extends AppStates{}
class PickProfileImageSuccessState extends AppStates{}
class UploadProfileImageSuccessState extends AppStates{}
class UploadProfileImageLoadingState extends AppStates{}
class UploadProfileImageErrorState extends AppStates{}
class UpdateUserErrorState extends AppStates{}
class UpdateUserSucessState extends AppStates{}
class AddToFavouriteSucessState extends AppStates{}
class ChangeFavState extends AppStates{}
class AddToFavouriteErrorState extends AppStates{}
class RemoveFavouriteSucessState extends AppStates{}
class RemoveFavouriteErrorState extends AppStates{}
class AddToCartSucessState extends AppStates{}
class RemoveFromCartSucessState extends AppStates{}
class Plus extends AppStates{}
class Subtract extends AppStates{}
class OrderSucessState extends AppStates{}
class GetOrderSucessState extends AppStates{}
class OrderErrorState extends AppStates{}
